# Generated by Django 5.0.2 on 2024-03-06 06:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(default='1234', max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, unique=True)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('national_ID', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=25)),
                ('second_name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=100)),
                ('user_role', models.CharField(max_length=25)),
                ('salary', models.IntegerField()),
                ('commission', models.IntegerField(default=0)),
                ('employee_login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='paramount.employeelogin')),
            ],
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total_income', models.IntegerField()),
                ('sales_date', models.DateField(validators=[django.core.validators.RegexValidator(code='invalid_date_format', message='Date must be in the format YYYY-MM-DD', regex='^\\d{4}-\\d{2}-\\d{2}$')])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paramount.employee')),
            ],
        ),
    ]
